name: homefix
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #state managemant
  flutter_bloc: ^8.1.6
  provider: ^6.0.5

  #generator
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4

  #local db
  shared_preferences: ^2.3.2

  #responsive_ui:
  flutter_screenutil: ^5.9.3

  #curved_navbar
  curved_navigation_bar: ^1.0.6

  #svg
  flutter_svg: ^2.0.10+1

  #calendar_table
  table_calendar: ^3.1.2
  intl:

  #localization
  easy_localization: ^3.0.0

  #uuid
  uuid: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
     - assets/svg/
     - lib/intl/
     - lib/intl/ru/symbols/
     - assets/intl/
     - assets/intl/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SourceSans3
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/SourceSans3-Medium.ttf
          style: normal
        - asset: assets/fonts/SourceSans3-Bold.ttf
          style: normal